name: a_check
description: An offline attendance management system with face recognition feature (thanks to MobileFaceNet) for checking attendance.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  calendar_view: ^1.0.4
  camera: ^0.10.5+5
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  google_mlkit_face_detection: ^0.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.1.3
  intl: ^0.18.1
  ml_algo: ^16.17.8
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  tflite_flutter: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/mobilefacenet.tflite
    - assets/images/