name: a_check
description: An attendance management app with face recognition feature (thanks to MobileFaceNet) for checking attendance.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  cloud_firestore: ^4.13.3
  cloud_firestore_odm: ^1.0.0-dev.78
  cloud_functions: ^4.5.8
  dropdown_search: ^5.0.6
  easy_onvif: ^2.1.2+13
  email_validator: ^2.1.17
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.4
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_vlc_player: ^7.4.0
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  google_mlkit_face_detection: ^0.8.0
  image: ^4.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  ml_algo: ^16.17.8
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  tflite_flutter: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  cloud_firestore_odm_generator: ^1.0.0-dev.78
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/mobilefacenet.tflite
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf