name: Build APK and create Release
on:
    release:
        types: [published]

jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '17'
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
            - name: Install dependencies
              run: flutter pub get --no-example
            - name: Build build_runner outputs
              run: dart run build_runner build --delete-conflicting-outputs
            - name: Create keystore
              id: decode_keystore
              uses: timheuer/base64-to-file@v1.2
              with:
                fileName: 'android_keystore.jks'
                fileDir: './android/app/keystore/'
                encodedString: ${{ secrets.KEYSTORE }}
            - name: Build APK
              run: flutter build apk --split-per-abi
              env:
                SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
                SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
                SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
            - name: Archive production artifact
              uses: actions/upload-artifact@v4
              with:
                name: apks
                path: build/app/outputs/apk/release/*.apk
    
    upload_release:
        name: Upload to release
        permissions: write-all
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: apks
            - name: Upload artifact to release
              env:
                GITHUB_TOKEN: ${{ github.token }}
              run: gh release upload ${{ github.event.release.tag_name }} app-arm64-v8a-release.apk app-armeabi-v7a-release.apk app-x86_64-release.apk
